general:
    attributes_to_read: #equal short names of netcdf-variables
        - TSurf
        - Albedo
        - WindSpd
        - T
        - LatentHeatFlux
    height_levels: 8
    removeOutputFiles: True
geoserver:
    url: http://localhost:8600/geoserver
    user: admin #password will be prompted in main.sh
    uploadTimeOut: 20 
styles: #To be defined in Hex Color Code
    DefaultColors: ["#0571b0","#92c5de","#f7f7f7","#f4a582","#ca0020"]
    customStyles:
        Albedo: #[optional]
            colors: ["#000000","#ffffff"]
            values: [0,1] #[optional]
